### PR TITLE
Create extension releases via GitHub Actions

### PR DESCRIPTION
**Pull request by bruwozniak**

### CODE REVIEW

**Comment by smaspe** [comment]
Is that creating a release on each commit to master?

**Comment by bruwozniak** [comment]
I think so, but also manual trigger would be possible

**Comment by smaspe** [comment]
The release name will simply be the sha-1 of the commit, right?

**Comment by bruwozniak** [comment]
I think so, I am not very familiar with GH actions yet so not sure how to trigger on "version release" yet.

**Review by smaspe — APPROVED** [review]

**Pull request merged**
